# Invoked with -DSPV_FILE=... -DHEADER_FILE=... -DSYMBOL=... by ninfer_embed_spirv_shader()
# (EmbedSpirv.cmake). Turns a compiled SPIR-V module into a byte array a C++ translation unit can
# embed, so the target binary needs neither the .spv file nor a shader compiler at runtime.
file(READ "${SPV_FILE}" hex_content HEX)
string(REGEX REPLACE "(..)" "0x\\1," byte_list "${hex_content}")
file(WRITE "${HEADER_FILE}"
"#pragma once
// Generated by cmake/EmbedSpirvGenerate.cmake from ${SPV_FILE}. Do not edit.
#include <cstddef>

alignas(4) inline constexpr unsigned char ${SYMBOL}_bytes[] = { ${byte_list} };
inline constexpr std::size_t ${SYMBOL}_size = sizeof(${SYMBOL}_bytes);
")
